apiVersion: v1
kind: Service
metadata:
  name: cdd-ui-probe-service
  namespace: data-discovery
  labels:
    app: cdd-probe
spec:
  ports:
    - name: http
      port: 8001
      targetPort: 9877
      protocol: TCP
  selector:
    app: cdd-probe
